### ISSUE TITLE
'x' must be numeric in 2_SPADE.R

### ISSUE THREAD

**Issue by ketancmaheshwari** [SofieVG/FlowCytometryScripts#2]
When I run 2_SPADE.R, I get the following error in PlotMarker function call that is at the end of  the script:

`Error in cut.default(fsom$map$meanValues[, marker], breaks = 100) : 
  'x' must be numeric
Calls: PlotMarker -> cut -> cut.default
`
Any help in how to debug the issue and possible root cause is greatly appreciated.

**Comment by ketancmaheshwari** [comment]
The script works when line 59 is replaced with:
`spade_res$map$meanValues`

**Comment by SofieVG** [comment]
This is an issue caused by different versions of the FlowSOM package, which is used to plot the SPADE results. Initially, mean values were used, but afterwards I switched to median values because those are more robust against outliers. This script assumed the newer version of the FlowSOM package. Your fix is indeed correct for the older FlowSOM version.
